import matplotlib.pyplot as plt
import numpy as np
# Kalibrierung
kalibrierung=np.genfromtxt("kalibrierung_2", delimiter=",")
plt.figure()
plt.plot(kalibrierung[:,0], kalibrierung[:,1], 'x', label="Kalibrierung")
#plt.plot(rawdata_2[:,0], rawdata_2[:,1], 'x', label="2. Filament ist an")
plt.xlabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.ylabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
#plt.errorbar(rawdata_1[:,0], rawdata_1[:,1], xerr=0.2, yerr=0.02, fmt='.', capsize=3, label="2. Filament ist aus")
#plt.errorbar(rawdata_2[:,0], rawdata_2[:,1], xerr=0.2, yerr=0.02, fmt='.', capsize=3, label="2. Filament ist an")
#plt.legend()
plt.savefig("Kalibrierung.pdf")
#plt.show()
plt.close()

# Temperaturabhaengigkeit
hysterese_7=np.genfromtxt("hysterese_7")
plt.figure()
plt.plot(hysterese_7[:,0], hysterese_7[:,1], 'x',label=r'$31.4\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_7_original.pdf")
plt.close()
# korrigierte hysterese kurven
plt.figure()
plt.plot(hysterese_7[:,0], hysterese_7[:,1]+0.00015 * hysterese_7[:,0] +0.02, 'x', label=r'$31.4\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_7.pdf")
plt.close()

# dies nun machen fuer alle hysterese kurven
hysterese_8 = np.genfromtxt("hysterese_8")
plt.figure()
#plt.plot(hysterese_8[:,0], hysterese_8[:,1], 'x', label="hysterese_8")
#print(hysterese_8[:,1]+0.00018 * hysterese_8[:,0] +0.22)
plt.plot(hysterese_8[:,0], hysterese_8[:,1]+0.00018 * hysterese_8[:,0] +0.22, 'x', label=r'$36.1\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_8.pdf")
plt.close()

hysterese_9 = np.genfromtxt("hysterese_9")
plt.figure()
#plt.plot(hysterese_9[:,0], hysterese_9[:,1], 'x', label="hysterese_9")
#print(hysterese_9[:,1]+0.00018 * hysterese_9[:,0] + 0.05)
plt.plot(hysterese_9[:,0], hysterese_9[:,1]+0.00018 * hysterese_9[:,0] +0.05 , 'x', label=r'$41.3\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_9.pdf")
plt.close()

hysterese_10 = np.genfromtxt("hysterese_10")
plt.figure()
#plt.plot(hysterese_10[:,0], hysterese_10[:,1], 'x', label="hysterese_10")
#print(hysterese_10[:,1]+0.0002 * hysterese_10[:,0] +0.43)
plt.plot(hysterese_10[:,0], hysterese_10[:,1]+0.0002 * hysterese_10[:,0] +0.43, 'x', label=r'$48.8\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_10.pdf")
plt.close()

hysterese_11 = np.genfromtxt("hysterese_11")
plt.figure()
#plt.plot(hysterese_11[:,0], hysterese_11[:,1], 'x', label="hysterese_10")
#print(hysterese_11[:,1]+0.00022 * hysterese_11[:,0] +0.24)
plt.plot(hysterese_11[:,0], hysterese_11[:,1]+0.00022 * hysterese_11[:,0] +0.24, 'x', label=r'$55.8\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_11.pdf")
plt.close()

hysterese_12 = np.genfromtxt("hysterese_12")
plt.figure()
#plt.plot(hysterese_12[:,0], hysterese_12[:,1], 'x', label="hysterese_12")
#print(hysterese_12[:,1]+0.00025 * hysterese_12[:,0] +0.29)
plt.plot(hysterese_12[:,0], hysterese_12[:,1]+0.00025 * hysterese_12[:,0] +0.29, 'x', label=r'$63.6\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_12.pdf")
plt.close()

hysterese_13 = np.genfromtxt("hysterese_13")
plt.figure()
#plt.plot(hysterese_13[:,0], hysterese_13[:,1], 'x', label="hysterese_13")
#print(hysterese_13[:,1]+0.00025 * hysterese_13[:,0] +0.31)
plt.plot(hysterese_13[:,0], hysterese_13[:,1]+0.00025 * hysterese_13[:,0] +0.31, 'x', label=r'$69.9\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_13.pdf")
plt.close()

hysterese_14 = np.genfromtxt("hysterese_14")
plt.figure()
#plt.plot(hysterese_14[:,0], hysterese_14[:,1], 'x', label="hysterese_14")
#print(hysterese_14[:,1]+0.00025 * hysterese_14[:,0] +0.295)
plt.plot(hysterese_14[:,0], hysterese_14[:,1]+0.00025 * hysterese_14[:,0] +0.295, 'x', label=r'$76.4\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_14.pdf")
plt.close()

hysterese_15 = np.genfromtxt("hysterese_15")
plt.figure()
#plt.plot(hysterese_15[:,0], hysterese_15[:,1], 'x', label="hysterese_15")
#print(hysterese_15[:,1]+0.00022 * hysterese_15[:,0] +0.27)
plt.plot(hysterese_15[:,0], hysterese_15[:,1]+0.00022 * hysterese_15[:,0] +0.27, 'x', label=r'$83,4\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_15.pdf")
plt.close()

hysterese_16 = np.genfromtxt("hysterese_16")
plt.figure()
#plt.plot(hysterese_16[:,0], hysterese_16[:,1], 'x', label="hysterese_16")
#print(hysterese_16[:,1]+0.00020 * hysterese_16[:,0] +0.19)
plt.plot(hysterese_16[:,0], hysterese_16[:,1]+0.00020 * hysterese_16[:,0] +0.19, 'x', label=r'$90.1\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_16.pdf")
plt.close()

hysterese_17 = np.genfromtxt("hysterese_17")
plt.figure()
#plt.plot(hysterese_17[:,0], hysterese_17[:,1], 'x', label="hysterese_17")
#print(hysterese_17[:,1]+0.00019 * hysterese_17[:,0] +0.1)
plt.plot(hysterese_17[:,0], hysterese_17[:,1]+0.00019 * hysterese_17[:,0] +0.1, 'x', label=r'$97.4\ {}^\circ\mathrm{C}$')
plt.ylabel(r'$\mathrm{Spannung}\   [\mathrm{V}] $')
plt.xlabel(r'$ \mathrm{Magnetfeld}\   [\mathrm{mT}]$' )
plt.legend()
plt.savefig("hysterese_17.pdf")
plt.close()

