import matplotlib.pyplot as plt
import numpy as np
# Spannung variieren
rawdata_1=np.genfromtxt("3_1_1_Filament_Spannung.dat", delimiter=",")
rawdata_2=np.genfromtxt("3_1_2_Filament_Spannung.dat", delimiter=",")
plt.figure()
plt.plot(rawdata_1[:,0], rawdata_1[:,1], 'x', label="2. Filament ist aus")
plt.plot(rawdata_2[:,0], rawdata_2[:,1], 'x', label="2. Filament ist an")
plt.legend()
plt.xlabel(r'$\mathrm{Entladungsspannung}\ U_{\mathrm{D}}\  [\mathrm{V}] $')
plt.ylabel(r'$ \mathrm{Entladungsstrom}\  I_{\mathrm{D}}\  [\mathrm{A}]$' )
plt.savefig("3_1_Spannung.pdf")
#plt.show()
plt.close()
# Stromstaerke variieren
rawdata_3=np.genfromtxt("3_1_1_Filament_Strom.dat", delimiter=",")
rawdata_4=np.genfromtxt("3_1_2_Filament_Strom.dat", delimiter=",")
plt.figure()
plt.plot(rawdata_3[:,0], rawdata_3[:,1], 'x', label="2. Filament ist aus")
plt.plot(rawdata_4[:,0], rawdata_4[:,1], 'x', label="2. Filament ist an")
plt.legend()
plt.xlabel(r'$\mathrm{Heizstrom}\ I_{\mathrm{H}}\  [\mathrm{A}] $')
plt.ylabel(r'$ \mathrm{Entladungsstrom}\  I_{\mathrm{D}}\  [\mathrm{A}]$' )
plt.savefig("3_1_Strom.pdf")
#plt.show()
plt.close()
# Druck  variieren
rawdata_5=np.genfromtxt("3_1_1_Filament_Druck.dat", delimiter=",")
rawdata_6=np.genfromtxt("3_1_2_Filament_Druck.dat", delimiter=",")
plt.figure()
plt.plot(rawdata_5[:,0], rawdata_5[:,1], 'x', label="2. Filament ist aus")
plt.plot(rawdata_6[:,0], rawdata_6[:,1], 'x', label="2. Filament ist an")
plt.legend()
plt.xlabel(r'$\mathrm{Druck}\ \mathrm{p}\  [\mathrm{mm}] $')
plt.ylabel(r'$ \mathrm{Entladungsstrom}\  I_{\mathrm{D}}\  [\mathrm{A}]$' )
plt.savefig("3_1_Druck.pdf")
#plt.show()
plt.close()
